name: hyperion

services:
  hyperion:
    image: "ghcr.io/hyperion-project/${distribution}:${codename}"
    platform: "${platform}"
    pull_policy: always
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: bash -c "set -x && apt-get update && apt-get install -y gpg apt-transport-https lsb-release && curl -sSL https://releases.hyperion-project.org/install | bash -s -- --verbose --${distribution} ${codename}"
    ports:
      - "19400:19400"
      - "19444:19444"
      - "19445:19445"
      - "8090:8090"
      - "8092:8092"
    volumes:
      - config:/home/hyperion:rw
    restart: unless-stopped
volumes:
  config: