name: DEB Packages build for APT Repository

on:
  workflow_call:
    inputs:
      repo_checkout:
        type: string
        description: The GitHub Repository to checkout
        default: hyperion-project
        required: false
      head_sha:
        type: string
        description: The branch, tag or SHA to checkout
        default: master
        required: false
      nightly:
        type: boolean
        description: Nightly build
        default: false
        required: false
      install_run_check:
        type: boolean
        description: Install & Run Check from APT Repository
        default: false
        required: false
      upload:
        type: boolean
        description: Upload Artifacts
        default: false
        required: false

env:
  repository: ${{ inputs.repo_checkout }}
  ghcr: hyperion-project

jobs:
  build:
    name: 🐧 ${{ matrix.os.description }} (${{ matrix.architecture[0] }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [
          { distribution: ubuntu, codename: focal,    description: Ubuntu 20.04 (Focal Fossa),     qt_version: '5' }, # Qt 6 not available
          { distribution: ubuntu, codename: jammy,    description: Ubuntu 22.04 (Jammy Jellyfish), qt_version: '6' },
          { distribution: ubuntu, codename: noble,    description: Ubuntu 24.04 (Noble Numbat),    qt_version: '6' },
          { distribution: debian, codename: buster,   description: Debian 10.x (Buster),           qt_version: '5' }, # Qt 6 not available
          { distribution: debian, codename: bullseye, description: Debian 11.x (Bullseye),         qt_version: '5' }, # Qt 6 only available from bullseye-backports
          { distribution: debian, codename: bookworm, description: Debian 12.x (Bookworm),         qt_version: '6' },
          { distribution: debian, codename: trixie,   description: Debian 13.x (Trixie),           qt_version: '6' }
        ]
        architecture: [
          [ amd64, linux/amd64  ],
          [ arm64, linux/arm64  ],
          [ armhf, linux/arm/v6 ],
          [ armhf, linux/arm/v7 ]
        ]
        exclude:
          - os: { distribution: ubuntu }
            architecture: [ armhf, linux/arm/v6 ]
          - os: { distribution: debian, codename: buster, }
            architecture: [ armhf, linux/arm/v7 ]
          - os: { distribution: debian, codename: bullseye, }
            architecture: [ armhf, linux/arm/v7 ]
          - os: { distribution: debian, codename: bookworm, }
            architecture: [ armhf, linux/arm/v7 ]
          - os: { distribution: debian, codename: trixie, } # Trixie armv6 not available yet (https://hub.docker.com/r/balenalib/rpi-raspbian/tags)
            architecture: [ armhf, linux/arm/v6 ]

    steps:

      # - name: 📥 Install & Run Check
      #   if: ${{ inputs.install_run_check }}
      #   id: install_run_check
      #   run: |

      - name: ⬇ Checkout hyperion.ng
        uses: actions/checkout@v4
        with:
          repository: ${{ env.repository }}/hyperion.ng
          ref: ${{ inputs.head_sha || 'master' }}
          submodules: recursive

      - name: ⬇ Checkout hyperion.releases-ci
        uses: actions/checkout@v4
        with:
          path: releases-ci

      - name: 🔧 Prepare
        run: |
          echo '::group::Checking the version number'
            if [[ "${{ inputs.nightly }}" = true ]]; then
              echo "$(tr -d '\n' < .version)+nightly$(date '+%Y%m%d')${{ inputs.head_sha }}" > .version
            else
              tr -d '\n' < .version > temp && mv temp .version
            fi
          echo '::endgroup::'

          echo '::group::Copy debian folder'
            cp -r releases-ci/debian ${GITHUB_WORKSPACE}/
          echo '::endgroup::'

      - name: 👷 Build
        uses: ./releases-ci/.github/actions/build
        with:
          distribution: ${{ matrix.os.distribution }}
          codename: ${{ matrix.os.codename }}
          architecture: ${{ matrix.architecture[0] }}
          qtVersion: ${{ matrix.os.qt_version }}
          ghcr: ${{ env.ghcr }}
          dockerArchitecture: ${{ matrix.architecture[1] }}

      # - name: 📦 Upload
      #   if: ${{ inputs.upload }} && ${{ !inputs.install_run_check || steps.install_run_check.outputs.force_build  == 'true' }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ format('artifact-{0}_{1}_{2}{3}', matrix.os.distribution, matrix.os.codename, matrix.architecture[0], matrix.os.qt_version  == '6' && '_qt6' || '')}}
      #     path: deploy
      #     retention-days: 1
          
