name: RPM Packages build for DNF Repository

on:
  workflow_call:
    inputs:
      repo_checkout:
        type: string
        description: The GitHub Repository to checkout (lower case)
        default: hyperion-project/hyperion.ng
        required: false
      head_sha:
        type: string
        description: The branch, tag or SHA to checkout (case sensitive)
        default: master
        required: false
      nightly:
        type: boolean
        description: Nightly build
        default: false
        required: false
      install_run_check:
        type: boolean
        description: Install & Run Check
        default: false
        required: false
      upload:
        type: boolean
        description: Upload Artifacts
        default: false
        required: false

env:
  ghcr: hyperion-project

jobs:
  build:
    name: 🐧 ${{ matrix.os.description }} (${{ matrix.architecture[0] }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [
          { distribution: fedora, version: 39, description: Fedora 39, qt_version: '6' },
          { distribution: fedora, version: 40, description: Fedora 40, qt_version: '6' }
        ]
        architecture: [
          [ amd64, linux/amd64 ]
        ]

    steps:
      # - name: 📥 Install & Run Check
      #   if: ${{ inputs.install_run_check }}
      #   id: install_run_check
      #   run: |

      - name: ⬇ Checkout hyperion.ng
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo_checkout }}
          ref: ${{ inputs.head_sha || 'master' }}
          submodules: recursive

      - name: ⬇ Checkout hyperion.releases-ci
        uses: actions/checkout@v4
        with:
          path: releases-ci

      - name: 🔧 Prepare
        run: |
          echo '::group::Checking the version number'
            if [[ "${{ inputs.nightly }}" = true ]]; then
              echo "$(tr -d '\n' < .version | sed s/-/_/g)+nightly$(date '+%Y%m%d')${{ inputs.head_sha }}" > .version
            else
              echo VERSION=$(tr -d '\n' < .version | sed s/-/_/g) >> $GITHUB_ENV
            fi
          echo '::endgroup::'

          echo '::group::Copy rpmbuild folder'
            cp -r releases-ci/rpmbuild ${GITHUB_WORKSPACE}/
          echo '::endgroup::'

      - name: 👷 Build
        uses: ./releases-ci/.github/actions/build
        with:
          distribution: ${{ matrix.os.distribution }}
          codename: ${{ matrix.os.version }}
          architecture: ${{ matrix.architecture[0] }}
          qtVersion: ${{ matrix.os.qt_version }}
          ghcr: ${{ env.ghcr }}
          dockerArchitecture: ${{ matrix.architecture[1] }}

      - name: 👷 Build
        shell: bash
        run: |
          echo '::group::Building Hyperion'
            mkdir -p "${GITHUB_WORKSPACE}/deploy"
            docker run --rm --platform=${{ matrix.architecture[1] }} \
              -w "/root" \
              -v "${GITHUB_WORKSPACE}/deploy:/deploy" \
              -v "${GITHUB_WORKSPACE}:/root/hyperion.ng:rw" \
              ghcr.io/${{ env.ghcr }}/$(echo '${{ matrix.os.distribution }}' | tr '[:upper:]' '[:lower:]'):${{ matrix.os.version }}-qt6 \
              /bin/bash -c "tar -czf rpmbuild/SOURCES/hyperion.ng.tar.gz hyperion.ng/ && \
              cp -f hyperion.ng/rpmbuild/hyperion.spec.in rpmbuild/SPECS/hyperion.spec && \
              rpmdev-bumpspec --comment='${{ env.COMMIT_MESSAGE }}' --userstring='${{ env.ACTOR }}' rpmbuild/SPECS/hyperion.spec && \
              rpmbuild -ba --define '_version ${{ env.VERSION }}' rpmbuild/SPECS/hyperion.spec --clean && \
              cp -fv rpmbuild/RPMS/$(uname -m)/hyperion* /deploy"
          echo '::endgroup::'
        env:
          ACTOR: "Hyperion Project <admin@hyperion-project.org>"
          COMMIT_MESSAGE: ${{ github.event.commits[0].message }}

      # - name: 📦 Upload
      #   if: ${{ inputs.upload }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ format('artifact-{0}_{1}_{2}_qt6', matrix.os.distribution, matrix.os.version, matrix.architecture[0] )}}
      #     path: deploy
      #     retention-days: 1
          
